Builder Design Pattern: Driver.cpp File Reference
Driver.cpp File Reference
#include "MazeGame.h"
#include "Maze.h"
#include "Builder.h"
Functions
void create_standard_maze ()
void create_counting_maze ()
int main ()
Function Documentation
void create_counting_maze ()
Definition at line 21 of file Driver.cpp.
References MazeGame::CreateMaze(), and CountingMazeBuilder::GetCounts().
Referenced by main().
void create_standard_maze ()
Definition at line 7 of file Driver.cpp.
References MazeGame::CreateMaze(), and StandardMazeBuilder::GetMaze().
Referenced by main().
int main ()
Definition at line 39 of file Driver.cpp.
References create_counting_maze(), and create_standard_maze().