Builder Design Pattern: MazeGame Class Reference
MazeGame Class Reference
#include <MazeGame.h>
Inherits Object.
Public Member Functions
MazeGame ()
virtual ~MazeGame ()
Maze * CreateMaze (MazeBuilder &builder)
Maze * CreateComplexMaze (MazeBuilder &builder)
virtual void Print (int indent=0)
Detailed Description
Definition at line 13 of file MazeGame.h.
Constructor & Destructor Documentation
MazeGame::MazeGame ()
Definition at line 10 of file MazeGame.cpp.
MazeGame::~MazeGame () [virtual]
Definition at line 12 of file MazeGame.cpp.
Member Function Documentation
Maze * MazeGame::CreateComplexMaze (MazeBuilder & builder)
Definition at line 25 of file MazeGame.cpp.
References MazeBuilder::BuildRoom(), and MazeBuilder::GetMaze().
Maze * MazeGame::CreateMaze (MazeBuilder & builder)
Definition at line 14 of file MazeGame.cpp.
References MazeBuilder::BuildDoor(), MazeBuilder::BuildMaze(), MazeBuilder::BuildRoom(), and MazeBuilder::GetMaze().
Referenced by create_counting_maze(), and create_standard_maze().
void MazeGame::Print (int indent = 0) [virtual]
Reimplemented from Object.
Definition at line 35 of file MazeGame.cpp.
References PrintIndent().
The documentation for this class was generated from the following files:
MazeGame.h
MazeGame.cpp