Builder Design Pattern: StandardMazeBuilder Class Reference
StandardMazeBuilder Class Reference
#include <Builder.h>
Inherits MazeBuilder.
Public Member Functions
StandardMazeBuilder ()
virtual void BuildMaze ()
virtual void BuildRoom (int)
virtual void BuildDoor (int, int)
virtual Maze * GetMaze ()
Private Member Functions
Direction CommonWall (Room *, Room *)
Private Attributes
Maze * _currentMaze
Detailed Description
Definition at line 22 of file Builder.h.
Constructor & Destructor Documentation
StandardMazeBuilder::StandardMazeBuilder ()
Definition at line 15 of file Builder.cpp.
References _currentMaze.
Member Function Documentation
void StandardMazeBuilder::BuildDoor (int n1, int n2) [virtual]
Reimplemented from MazeBuilder.
Definition at line 45 of file Builder.cpp.
References _currentMaze, CommonWall(), Maze::RoomNo(), and Room::SetSide().
void StandardMazeBuilder::BuildMaze () [virtual]
Reimplemented from MazeBuilder.
Definition at line 20 of file Builder.cpp.
References _currentMaze.
void StandardMazeBuilder::BuildRoom (int n) [virtual]
Reimplemented from MazeBuilder.
Definition at line 31 of file Builder.cpp.
References _currentMaze, Maze::AddRoom(), East, North, Maze::RoomNo(), Room::SetSide(), South, and West.
Direction StandardMazeBuilder::CommonWall (Room * , Room *) [inline, private]
Definition at line 34 of file Builder.h.
References East.
Referenced by BuildDoor().
Maze * StandardMazeBuilder::GetMaze () [virtual]
Reimplemented from MazeBuilder.
Definition at line 25 of file Builder.cpp.
References _currentMaze.
Referenced by create_standard_maze().
Member Data Documentation
Maze* StandardMazeBuilder::_currentMaze [private]
Definition at line 41 of file Builder.h.
Referenced by BuildDoor(), BuildMaze(), BuildRoom(), GetMaze(), and StandardMazeBuilder().
The documentation for this class was generated from the following files:
Builder.h
Builder.cpp