Builder Design Pattern: Maze Class Reference
Maze Class Reference
#include <Maze.h>
Inherits Object.
Public Member Functions
Maze ()
virtual ~Maze ()
void AddRoom (class Room *)
class Room * RoomNo (int) const
virtual void Print (int indent=0)
Private Attributes
class ObjectArray * Rooms
Detailed Description
Definition at line 12 of file Maze.h.
Constructor & Destructor Documentation
Maze::Maze ()
Definition at line 7 of file Maze.cpp.
References Rooms.
Maze::~Maze () [virtual]
Definition at line 12 of file Maze.cpp.
References Rooms.
Member Function Documentation
void Maze::AddRoom (class Room * room)
Definition at line 17 of file Maze.cpp.
References Room::GetRoomNo(), ObjectArray::PutAt(), and Rooms.
Referenced by StandardMazeBuilder::BuildRoom().
void Maze::Print (int indent = 0) [virtual]
Reimplemented from Object.
Definition at line 27 of file Maze.cpp.
References ObjectArray::Print(), PrintIndent(), and Rooms.
class Room * Maze::RoomNo (int roomNo) const
Definition at line 21 of file Maze.cpp.
References ObjectArray::GetAt(), and Rooms.
Referenced by StandardMazeBuilder::BuildDoor(), and StandardMazeBuilder::BuildRoom().
Member Data Documentation
class ObjectArray* Maze::Rooms [private]
Definition at line 24 of file Maze.h.
Referenced by AddRoom(), Maze(), Print(), RoomNo(), and ~Maze().
The documentation for this class was generated from the following files:
Maze.h
Maze.cpp