Builder Design Pattern: Room Class Reference
Room Class Reference
#include <Room.h>
Inherits MapSite.
Public Member Functions
Room (int roomNo)
virtual ~Room ()
class MapSite * GetSide (Direction) const
int GetRoomNo () const
void SetSide (Direction, class MapSite *)
virtual void Enter ()
virtual void Print (int indent=0)
Private Attributes
class ObjectArray * _sides
int _roomNumber
Detailed Description
Definition at line 13 of file Room.h.
Constructor & Destructor Documentation
Room::Room (int roomNo)
Definition at line 6 of file Room.cpp.
References _roomNumber, and _sides.
Room::~Room () [virtual]
Definition at line 12 of file Room.cpp.
References _sides.
Member Function Documentation
void Room::Enter () [virtual]
Implements MapSite.
Definition at line 29 of file Room.cpp.
int Room::GetRoomNo () const
Definition at line 21 of file Room.cpp.
References _roomNumber.
Referenced by Maze::AddRoom(), and Door::Print().
class MapSite * Room::GetSide (Direction d) const
Definition at line 17 of file Room.cpp.
References _sides, and ObjectArray::GetAt().
void Room::Print (int indent = 0) [virtual]
Reimplemented from MapSite.
Definition at line 33 of file Room.cpp.
References _roomNumber, _sides, ObjectArray::Print(), and PrintIndent().
void Room::SetSide (Direction d, class MapSite * ms)
Definition at line 25 of file Room.cpp.
References _sides, and ObjectArray::PutAt().
Referenced by StandardMazeBuilder::BuildDoor(), and StandardMazeBuilder::BuildRoom().
Member Data Documentation
int Room::_roomNumber [private]
Definition at line 30 of file Room.h.
Referenced by GetRoomNo(), Print(), and Room().
class ObjectArray* Room::_sides [private]
Definition at line 29 of file Room.h.
Referenced by GetSide(), Print(), Room(), SetSide(), and ~Room().
The documentation for this class was generated from the following files:
Room.h
Room.cpp