Builder Design Pattern: MazeBuilder Class Reference
MazeBuilder Class Reference
#include <Builder.h>
Inherited by CountingMazeBuilder, and StandardMazeBuilder.
Public Member Functions
virtual void BuildMaze ()
virtual void BuildRoom (int room)
virtual void BuildDoor (int roomFrom, int roomTo)
virtual Maze * GetMaze ()
Protected Member Functions
MazeBuilder ()
Detailed Description
Definition at line 11 of file Builder.h.
Constructor & Destructor Documentation
MazeBuilder::MazeBuilder () [inline, protected]
Definition at line 19 of file Builder.h.
Member Function Documentation
virtual void MazeBuilder::BuildDoor (int roomFrom, int roomTo) [inline, virtual]
Reimplemented in StandardMazeBuilder, and CountingMazeBuilder.
Definition at line 15 of file Builder.h.
Referenced by MazeGame::CreateMaze().
virtual void MazeBuilder::BuildMaze () [inline, virtual]
Reimplemented in StandardMazeBuilder, and CountingMazeBuilder.
Definition at line 13 of file Builder.h.
Referenced by MazeGame::CreateMaze().
virtual void MazeBuilder::BuildRoom (int room) [inline, virtual]
Reimplemented in StandardMazeBuilder, and CountingMazeBuilder.
Definition at line 14 of file Builder.h.
Referenced by MazeGame::CreateComplexMaze(), and MazeGame::CreateMaze().
virtual Maze* MazeBuilder::GetMaze () [inline, virtual]
Reimplemented in StandardMazeBuilder.
Definition at line 17 of file Builder.h.
Referenced by MazeGame::CreateComplexMaze(), and MazeGame::CreateMaze().
The documentation for this class was generated from the following file:
Builder.h