Builder Design Pattern: Restaurant.cpp File Reference
Restaurant.cpp File Reference
#include "Pizza.h"
#include "PizzaBuilder.h"
#include "HawaiianPizzaBuilder.h"
#include "SpicyPizzaBuilder.h"
#include "Waiter.h"
Functions
int main ()
Function Documentation
int main ()
Definition at line 8 of file Restaurant.cpp.
References Waiter::ConstructPizza(), Waiter::GetPizza(), and Waiter::SetPizzaBuilder().