Builder Design Pattern: Waiter Class Reference
Waiter Class Reference
#include <Waiter.h>
Public Member Functions
Waiter ()
~Waiter ()
void SetPizzaBuilder (PizzaBuilder *b)
std::auto_ptr< Pizza > GetPizza ()
void ConstructPizza ()
Private Attributes
PizzaBuilder * pizzaBuilder
Detailed Description
Definition at line 2 of file Waiter.h.
Constructor & Destructor Documentation
Waiter::Waiter () [inline]
Definition at line 7 of file Waiter.h.
Waiter::~Waiter () [inline]
Definition at line 8 of file Waiter.h.
Member Function Documentation
void Waiter::ConstructPizza () [inline]
Definition at line 12 of file Waiter.h.
References PizzaBuilder::buildDough(), PizzaBuilder::buildSauce(), PizzaBuilder::buildTopping(), PizzaBuilder::createNewPizzaProduct(), and pizzaBuilder.
Referenced by main().
std::auto_ptr<Pizza> Waiter::GetPizza () [inline]
Definition at line 11 of file Waiter.h.
References PizzaBuilder::GetPizza(), and pizzaBuilder.
Referenced by main().
void Waiter::SetPizzaBuilder (PizzaBuilder * b) [inline]
Definition at line 10 of file Waiter.h.
References pizzaBuilder.
Referenced by main().
Member Data Documentation
PizzaBuilder* Waiter::pizzaBuilder [private]
Definition at line 5 of file Waiter.h.
Referenced by ConstructPizza(), GetPizza(), and SetPizzaBuilder().
The documentation for this class was generated from the following file:
Waiter.h