Builder Design Pattern: PizzaBuilder Class Reference
PizzaBuilder Class Reference
#include <PizzaBuilder.h>
Inherited by HawaiianPizzaBuilder, and SpicyPizzaBuilder.
Public Member Functions
PizzaBuilder ()
virtual ~PizzaBuilder ()
std::auto_ptr< Pizza > GetPizza ()
void createNewPizzaProduct ()
virtual void buildDough ()=0
virtual void buildSauce ()=0
virtual void buildTopping ()=0
Protected Attributes
std::auto_ptr< Pizza > pizza
Detailed Description
Definition at line 2 of file PizzaBuilder.h.
Constructor & Destructor Documentation
PizzaBuilder::PizzaBuilder () [inline]
Definition at line 7 of file PizzaBuilder.h.
virtual PizzaBuilder::~PizzaBuilder () [inline, virtual]
Definition at line 8 of file PizzaBuilder.h.
Member Function Documentation
virtual void PizzaBuilder::buildDough () [pure virtual]
Implemented in HawaiianPizzaBuilder, and SpicyPizzaBuilder.
Referenced by Waiter::ConstructPizza().
virtual void PizzaBuilder::buildSauce () [pure virtual]
Implemented in HawaiianPizzaBuilder, and SpicyPizzaBuilder.
Referenced by Waiter::ConstructPizza().
virtual void PizzaBuilder::buildTopping () [pure virtual]
Implemented in HawaiianPizzaBuilder, and SpicyPizzaBuilder.
Referenced by Waiter::ConstructPizza().
void PizzaBuilder::createNewPizzaProduct () [inline]
Definition at line 11 of file PizzaBuilder.h.
References pizza.
Referenced by Waiter::ConstructPizza().
std::auto_ptr<Pizza> PizzaBuilder::GetPizza () [inline]
Definition at line 9 of file PizzaBuilder.h.
References pizza.
Referenced by Waiter::GetPizza().
Member Data Documentation
std::auto_ptr<Pizza> PizzaBuilder::pizza [protected]
Definition at line 5 of file PizzaBuilder.h.
Referenced by SpicyPizzaBuilder::buildDough(), HawaiianPizzaBuilder::buildDough(), SpicyPizzaBuilder::buildSauce(), HawaiianPizzaBuilder::buildSauce(), SpicyPizzaBuilder::buildTopping(), HawaiianPizzaBuilder::buildTopping(), createNewPizzaProduct(), and GetPizza().
The documentation for this class was generated from the following file:
PizzaBuilder.h